version: "3.3"
services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_USER=adminpostgres
      - POSTGRES_PASSWORD=87654321
    ports:
      # <Port exposed> : < Postgres Port running inside container>
      - "5432:5432"
    expose:
      # Opens port 5432 on the container
      - "5432"
      # Where our data will be persisted
    volumes:
      - /home/yahfiilham/database-docker/postgres:/var/lib/postgresql/data
      # - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.4
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:5.3.1
    depends_on:
      - zookeeper
    ports:
      - 9093:9093
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9998
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka1 -Dcom.sun.management.jmxremote.rmi.port=9998
  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - zookeeper
      - kafka

  ## Microservices
  input-harga-service:
    build:
      context: ../microservices/input-harga-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    environment:
      WAIT_HOSTS: postgres:5432, kafka:9093, zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
  input-harga-storage-service:
    build:
      context: ../microservices/input-harga-storage-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: always
    environment:
      WAIT_HOSTS: postgres:5432, kafka:9093, zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
  check-harga-service:
    build:
      context: ../microservices/check-harga-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    restart: always
    environment:
      WAIT_HOSTS: postgres:5432, kafka:9093, zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
  topup-service:
    build:
      context: ../microservices/topup-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    restart: always
    environment:
      WAIT_HOSTS: postgres:5432, kafka:9093, zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
  topup-storage-service:
    build:
      context: ../microservices/topup-storage-service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    restart: always
    environment:
      WAIT_HOSTS: postgres:5432, kafka:9093, zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
  check-saldo-service:
    build:
      context: ../microservices/check-saldo-service
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    restart: always
    environment:
      WAIT_HOSTS: postgres:5432, kafka:9093, zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
  check-mutasi-service:
    build:
      context: ../microservices/check-mutasi-service
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    restart: always
    environment:
      WAIT_HOSTS: postgres:5432, kafka:9093, zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
  buyback-service:
    build:
      context: ../microservices/buyback-service
      dockerfile: Dockerfile
    ports:
      - "8007:8007"
    restart: always
    environment:
      WAIT_HOSTS: postgres:5432, kafka:9093, zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
  buyback-storage-service:
    build:
      context: ../microservices/buyback-storage-service
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    restart: always
    environment:
      WAIT_HOSTS: postgres:5432, kafka:9093, zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
